name: github-acitons

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check go version
        run: go version

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./cmd/taskgo/

      - name: Test
        run: go test -race -v ./...

      - name: Benchmark
        run: go test -bench=. -benchtime=5s -run=Bench -v ./...
