name: golangci-lint
on:
  push:
    branches:
      - main
      - github-actions
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --print-issued-lines=false --out-format=colored-line-number --issues-exit-code=0
